apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.config.configMapName }}
  labels:
    app: {{ .Values.app.name }}
data:
  SPRING_MONGODB_URI: {{ .Values.config.mongodb.uri }}
  OTEL_EXPORTER_OTLP_ENDPOINT: {{ .Values.config.otel.endpoint }}
