apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.config.configMapName }}
  labels:
    app: {{ .Values.app.name }}
data:
  SPRING_DATA_MONGODB_URI: mongodb://mongodb:27017
  OTEL_EXPORTER_OTLP_ENDPOINT: http://otelcol:4317
