replicaCount: 1

image:
  pullPolicy: IfNotPresent
  tag: "1.0"
  name: todo-api

app:
  name: todo-api
  rootPath: "/"

config:
  configMapName: todo-api-config
  mongodb:
    uri: mongodb://mongo:27017
  otel:
    endpoint: http://otelcol:4317

resources:
  limits:
    cpu: "2"
    memory: "1Gi"
  requests:
    cpu: "1"
    memory: "512Mi"

service:
  type: ClusterIP
  ports:
    - name: http
      type: ClusterIP
      port: 80
      targetPort: 8080
      protocol: TCP
